{% set name = "djangorestframework-csv" %}
{% set version = "3.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/djangorestframework-csv-{{ version }}.tar.gz
  sha256: b269b692feda1971e1342f395a21d339c6a16d2961ff64357a9a6188f27af10f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - djangorestframework

test:
  imports:
    - rest_framework_csv
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mjumbewu/django-rest-framework-csv
  summary: CSV Tools for Django REST Framework
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
